version: '3.1'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: todolistv2
    ports:
     - "3000:3000"
    volumes:
     - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: todolistv2-db
    restart: always
    tty: true
    ports:
     - "5432:5432"
    volumes:
     - .docker/dbdata:/var/lib/postgres/data
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=todolistv2
    